"""Add poll_manually_ended field

Revision ID: f0aa27b52bf2
Revises: d2aa9a7840db
Create Date: 2025-08-07 19:19:10.213349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0aa27b52bf2'
down_revision: Union[str, Sequence[str], None] = 'd2aa9a7840db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_settings', sa.Column('poll_manually_ended', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_settings', 'poll_manually_ended')
    # ### end Alembic commands ###
